version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/eslint-config'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'

    - package-ecosystem: 'npm'
      directory: '/prettier-config'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'
