version: 2.1
orbs:
  gh: circleci/github-cli@1.0.3
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Verify Artifacts
          command: cd eslint-config && yarn test && cd ../prettier-config && yarn test

  publish:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command:  |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish @brightlayer-ui/prettier-config
          command: cd prettier-config && yarn publish:package -b $CIRCLE_BRANCH
      - run:
          name: Publish @brightlayer-ui/eslint-config
          command: cd eslint-config && yarn publish:package -b $CIRCLE_BRANCH

workflows:
  version: 2
  code_standards:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
